branch-defaults:
  master:
    environment: mga-prod-env
  staging:
    environment: null
global:
  application_name: mga-assessment-tool
  default_ec2_keyname: rgi-tool
  default_platform: 64bit Amazon Linux 2015.03 v1.4.1 running Docker 1.6.0
  default_region: us-east-1
  profile: eb-cli
  sc: git
