branch-defaults:
  master:
    environment: mgaAssessmentTool-env
global:
  application_name: mga-assessment-tool
  default_ec2_keyname: rgi-tool
  default_platform: Docker 1.6.0
  default_region: us-east-1
  profile: eb-cli
  sc: git
